#!/bin/bash

set -e

GOVERS=1.10

mkdir -p \
	$HOME/.local/go/$GOVERS \
	$HOME/go

echo "::: install Go ${GOVERS}..."
curl -O -L https://golang.org/dl/go${GOVERS}.linux-amd64.tar.gz
tar -C $HOME/.local/go/$GOVERS -zxf go${GOVERS}.linux-amd64.tar.gz
/bin/rm go${GOVERS}.linux-amd64.tar.gz

export GOROOT=$HOME/.local/go/$GOVERS/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

echo "::: installing neugram..."
go get golang.org/x/tools/cmd/goimports
go get neugram.io/ng/...
echo "::: installing neugram... [done]"

## setup environment for Go

cat >> $HOME/.setup-go << EOF
## setup Go
export GOROOT=$GOROOT
export GOPATH=$GOPATH
export PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH
EOF

cat >> $HOME/.bashrc << EOF
. ~/.setup-go
EOF

## install the Go kernel
git clone https://github.com/neugram/binder
cat >| ./binder/neugram/kernel.json << EOF
{
    "argv": [
        "$GOPATH/bin/ng", "-jupyter",
        "{connection_file}"
    ],
    "display_name": "Neugram",
    "language": "neugram",
    "name": "ng",
    "env": {
        "GOPATH": "$GOPATH",
        "GOROOT": "$GOROOT",
        "PATH":   "$GOPATH/bin:$GOROOT/bin:$PATH"
	}
}
EOF
jupyter kernelspec install ./binder/neugram --user

/bin/rm -rf binder

echo "::: kernel list"
jupyter kernelspec list
